name: AutoCoder Workflow

on:
  push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # actions/checkout
        uses: actions/checkout@v2

      - name: Greeting Message
        run: echo "Hello, world!"